name: OCCT examples
description: Open CASCADE Technology - live Draw Harness examples
author: Kirill Gavrilov
author_email: kirill@sview.ru

# The directory for category index pages.
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /occt-examples
#baseurl: /
baseurl:

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: https://gkv311.github.io/occt-examples/
#url: https://draw.sview.ru/

#### Under the Hood Stuff #####

plugins:
  - jekyll-sitemap

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
#markdown: rdiscount

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
#permalink: pretty
permalink: /:categories/:title/

# How many articles do you wish to appear on the front page:
paginate: 3

#markdown: kramdown
#highlighter: rouge

collections:
  examples:
#    output: true

include: [_examples]
includes_dir: _examples

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, repository, gallery, deploy.sh]

#excerpt_separator: <!--more-->
excerpt_separator: <!--break-->

occt_wasm:    "/occt-draw"
occt_docs:    "https://dev.opencascade.org/doc/overview/html"
occt_refman:  "https://dev.opencascade.org/doc/refman/html"
